To Do:
*  Provide stats such as:
  -  Best/Worst team (based on points assigned to their winnings)
  -  Biggest upsetter / Best picker (based on how many points they made people loose/win)
*  Update session timeout - make it longer
*  On Home page
  - provide link to this week's picks
  - provide link to last week's results
  - status if picks have been done or not
  - provide admin link for admins
*  Create a sanity check page
  - Check that no team plays twice in the same week.
  - Check that no team has more than one bye week.
  - Check that the start of the week is the same as the first game of that week.
  - Check that all games of the same week are in the same calendar week
*  Disable submit button if errors
*  Email forgotten password form?
*  Check for XSS and SQL Injection
*  Add all the games
*  Menu
*  On picking page, show data that picks need to be done by
*  Show date/times of games

Done:
*  Be able to add new games / weeks / years
*  Be able to do picks
*  Be able to edit picks
*  Use real complete HTML pages
*  Use CSS
*  Set up current year, so we can do more than one year / playoffs
*  Set up https - run it on a non-standard port
*  Verify can't have duplicate email addresses
*  Updateing of team records
*  Verify can't change picks after start of week
*  Group Stats
*  Page to update groups stats so we're not generating them on the fly all the time
*  Results page
*  Admin interface to update picks / points for players and records for teams
*  Registration Page
*  Verify that names are displayed w/ htmlentities!!
*  Provide status message when picks are saved.
*  Test in IE
*  On Admin page
  - Check who has and who has not done their picks
